name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm test
      - name: Integration tests
        run: npm run test:integration:docker
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.DISPATCH_CI_TOKEN }}
          event-type: ci-finished
